# Generated by Django 5.1 on 2024-08-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_district_options_alter_region_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('social', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'Youtube')], max_length=16)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['order_id', 'id']},
        ),
    ]
